// Civilbook - Codigo proprietario. (c) 2026 CB Desenvolvimento de Software Não Customizável Inova Simples (I.S.).
// Todos os direitos reservados. Proibida copia, redistribuicao, modificacao ou
// uso sem autorizacao escrita do titular. Ver LICENSE (Lei 9.609/98 e 9.610/98).
// Componentes de terceiros mantem suas proprias licencas.
function rowToOrc(t){return{id:t.id,projeto_id:t.projeto_id||"",nome:t.nome||"",uf:t.uf||"",regime:t.regime||"",bdi:t.bdi!=null?t.bdi:0,itens:t.itens||[],versao:t.versao||1,obs:t.obs||"",dono:t.user_id}}function orcToRow(t){return{id:t.id,user_id:t.dono||CBStore.uid(),projeto_id:t.projeto_id||null,nome:t.nome||"Orçamento",uf:t.uf||null,regime:t.regime||null,bdi:Number(t.bdi)||0,itens:t.itens||[],versao:t.versao||1,obs:t.obs||null}}const ORC=cbColecao("obra_orcamentos","cb-obra-orcamentos",rowToOrc,orcToRow);let _orcPane=null;let _orcAberto=null;let _orcBusca="";function orcBRL(t){return(Number(t)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}function orcNum(t){return String(Number(t)||0).replace(".",",")}function orcNorm(t){return String(t||"").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,"")}async function renderOrcamento(t){_orcPane=t||_orcPane;if(!_orcPane)return;if(!planoEhPro()){_orcPane.innerHTML=orcUpsellHTML();return}_orcPane.innerHTML=`<p class="page-sub">Carregando…</p>`;if(!ORC._loaded)await ORC.ready();try{if(typeof SINAPIDB!=="undefined")await SINAPIDB.ready()}catch(e){}if(typeof MODULOS!=="undefined"){try{await MODULOS.garantir("projetos")}catch(e){}}if(typeof PROJ!=="undefined"&&!PROJ._loaded&&typeof proj2Ready==="function"){try{await proj2Ready()}catch(e){}}orcRender()}function orcRender(){if(!_orcPane)return;if(_orcAberto&&ORC.get(_orcAberto))_orcPane.innerHTML=orcEditorHTML(ORC.get(_orcAberto));else{_orcAberto=null;_orcPane.innerHTML=orcListaHTML()}}function orcUpsellHTML(){return`<div class="card" style="max-width:560px;margin:30px auto;text-align:center;padding:32px">
    <div class="card-icon" style="background:var(--blue-light);color:var(--blue);margin:0 auto 14px"><i class="ti ti-file-invoice"></i></div>
    <h3 style="font-size:18px;font-weight:600;margin-bottom:8px">Orçamento de obra é um recurso PRO</h3>
    <p style="color:var(--text-2);margin-bottom:18px">Componha o orçamento com composições SINAPI + itens avulsos, BDI e resumo por etapa, salve por obra e exporte.</p>
    ${typeof cbTesteBotaoHTML==="function"?cbTesteBotaoHTML("sinapi","orc:","btn primary"):""}
    ${typeof EXEMPLO!=="undefined"?EXEMPLO.botaoUpsellHTML("orcamento"):""}
  </div>`}function orcListaHTML(){const t=ORC.listar().slice().sort((e,i)=>(e.nome||"").localeCompare(i.nome||""));return`
    <p class="page-sub">Componha o orçamento da obra a partir das composições SINAPI (preço da UF/regime escolhidos acima na aba SINAPI) e de itens avulsos, com BDI e resumo por etapa. Material de apoio — BDI e preços finais são responsabilidade do RT.</p>
    <div style="margin:12px 0;display:flex;gap:10px;flex-wrap:wrap"><button class="btn primary" onclick="orcNovo()"><i class="ti ti-plus"></i> Novo orçamento</button>${typeof EXEMPLO!=="undefined"?EXEMPLO.botaoBarraHTML("orcamento"):""}<button class="btn" onclick="cbAssessor('abrirCom','orcamento')" title="Abrir o assessor já sabendo que você está no Orçamento (f40)"><i class="ti ti-sparkles" aria-hidden="true"></i> Perguntar à IA</button></div>
    ${t.length===0?typeof EXEMPLO!=="undefined"?EXEMPLO.vazioHTML("orcamento",{icone:"ti-calculator",titulo:"Monte o orçamento da obra",texto:"Puxe composições da base SINAPI (na UF e no regime que você escolher), acrescente itens avulsos, aplique o BDI e veja o resumo por etapa — pronto para imprimir e para comparar com o realizado.",ctaLabel:"Criar o primeiro orçamento",ctaAcao:"orcNovo()"}):`<p class="page-sub" style="text-align:center;padding:18px">Nenhum orçamento ainda.</p>`:t.map(e=>{const i=orcTotais(e);return`<div class="card clickable" onclick="orcAbrir('${e.id}')" style="display:flex;justify-content:space-between;align-items:center;gap:12px">
          <div><div style="font-weight:600">${esc(e.nome||"Orçamento")} <span class="page-sub" style="font-size:11px">v${e.versao||1}</span></div>
            <div class="page-sub" style="margin:2px 0 0;font-size:12px">${esc(orcProjNome(e))} · ${i.n} ${i.n===1?"item":"itens"} · ${orcBRL(i.total)} (c/ BDI ${i.bdiPct}%)</div></div>
          <i class="ti ti-chevron-right" style="color:var(--text-3)"></i></div>`}).join("")}`}function orcProjNome(t){if(t.projeto_id&&typeof PROJ!=="undefined"&&PROJ.get(t.projeto_id))return PROJ.get(t.projeto_id).nome;return t.nome||"Obra"}function orcNovo(){const t=typeof SINAPIDB!=="undefined"?SINAPIDB.meta():{};const e=CBStore.uuid();ORC.upsert({id:e,nome:"Orçamento "+(ORC.listar().length+1),projeto_id:"",uf:t.uf||"",regime:t.regime||"SD",bdi:0,itens:[],versao:1,obs:"",dono:CBStore.uid()});_orcAberto=e;orcRender()}function orcAbrir(t){_orcAberto=t;_orcBusca="";orcRender()}function orcVoltar(){_orcAberto=null;orcRender()}async function orcExcluir(t){if(!await cbConfirmar("Excluir este orçamento? A ação não pode ser desfeita."))return;ORC.remover(t);_orcAberto=null;orcRender()}function orcDuplicar(t){const e=ORC.get(t);if(!e)return;const i=CBStore.uuid();ORC.upsert({id:i,nome:e.nome,projeto_id:e.projeto_id,uf:e.uf,regime:e.regime,bdi:e.bdi,itens:(e.itens||[]).map(o=>Object.assign({},o,{id:CBStore.uuid()})),versao:(e.versao||1)+1,obs:e.obs,dono:CBStore.uid()});toast("Nova versão criada (v"+((e.versao||1)+1)+").","success");_orcAberto=i;orcRender()}function orcMeta(t,e,i){const o=ORC.get(t);if(!o)return;o[e]=e==="bdi"?Math.max(0,Number(i)||0):i;ORC.upsert(o);orcRender()}function orcItemAvulso(t){const e=ORC.get(t);if(!e)return;e.itens=(e.itens||[]).concat([{id:CBStore.uuid(),etapa:"",tipo:"avulso",codigo:"",descricao:"Item avulso",unidade:"un",qtd:1,pu:0}]);ORC.upsert(e);orcRender()}function orcAddSinapi(t,e){const i=ORC.get(t);if(!i)return;const o=typeof SINAPIDB!=="undefined"?SINAPIDB.lista().find(a=>a.codigo===e):null;if(!o)return;i.itens=(i.itens||[]).concat([{id:CBStore.uuid(),etapa:"",tipo:"sinapi",codigo:o.codigo,descricao:o.descricao,unidade:o.unidade||"un",qtd:1,pu:o.preco!=null?o.preco:0}]);ORC.upsert(i);_orcBusca="";orcRender()}function orcItemRemove(t,e){const i=ORC.get(t);if(!i)return;i.itens=(i.itens||[]).filter(o=>o.id!==e);ORC.upsert(i);orcRender()}function orcItemSet(t,e,i,o){const a=ORC.get(t);if(!a)return;const r=(a.itens||[]).find(n=>n.id===e);if(!r)return;r[i]=i==="qtd"||i==="pu"?Math.max(0,Number(o)||0):o;ORC.upsert(a);orcRenderResumo(t)}function orcRenderResumo(t){const e=ORC.get(t),i=document.getElementById("orc-resumo");if(e&&i)i.innerHTML=orcResumoHTML(e)}let _orcBuscaTO=null;function orcBuscar(t,e){_orcBusca=e;clearTimeout(_orcBuscaTO);_orcBuscaTO=setTimeout(()=>{const i=document.getElementById("orc-result");if(!i)return;const o=orcNorm(e).trim();if(o.length<2||typeof SINAPIDB==="undefined"){i.innerHTML="";return}const a=SINAPIDB.lista()||[];const r=[];for(let n=0;n<a.length&&r.length<25;n++){const s=a[n];if(orcNorm(s.codigo).indexOf(o)>=0||orcNorm(s.descricao).indexOf(o)>=0)r.push(s)}i.innerHTML=r.length?r.map(n=>`<div class="orc-hit" onclick="orcAddSinapi('${t}','${esc(n.codigo)}')" role="button" tabindex="0">
          <span class="orc-hit-cod">${esc(n.codigo)}</span>
          <span class="orc-hit-desc">${esc(n.descricao)}</span>
          <span class="orc-hit-pu">${n.preco!=null?orcBRL(n.preco)+"/"+esc(n.unidade||"un"):"sem preço"}</span></div>`).join(""):`<div class="page-sub" style="padding:8px">Nenhuma composição para “${esc(e)}”.</div>`},220)}function orcTotais(t){const e=t.itens||[],i={};let o=0;e.forEach(n=>{const s=(Number(n.qtd)||0)*(Number(n.pu)||0);const c=n.etapa||"(sem etapa)";i[c]=(i[c]||0)+s;o+=s});const a=Number(t.bdi)||0,r=o*a/100;return{porEtapa:i,direto:o,bdiPct:a,bdiVal:r,total:o+r,n:e.length}}function orcEditorHTML(t){const e=typeof PROJ!=="undefined"?PROJ.listar():[];const i=`<option value="">— sem projeto —</option>`+e.map(r=>`<option value="${esc(r.id)}"${r.id===t.projeto_id?" selected":""}>${esc(r.nome)}</option>`).join("");const o=typeof SINAPIDB!=="undefined"?SINAPIDB.meta():{};const a=o.uf?`SINAPI ${esc(o.uf)} · ${esc(SINAPIDB._regimeLabel?SINAPIDB._regimeLabel(o.regime):o.regime||"")}${o.competencia?" · "+esc(SINAPIDB.fmtCompet(o.competencia)):""}`:"base estática";return`
    <div class="no-print" style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:12px">
      <button class="back-link" onclick="orcVoltar()"><i class="ti ti-arrow-left"></i> Todos os orçamentos</button>
      <div style="display:flex;gap:8px;flex-wrap:wrap">
        <button class="btn sm" onclick="orcCSV('${t.id}')"><i class="ti ti-table-export"></i> CSV (Excel)</button>
        <button class="btn sm" onclick="window.print()"><i class="ti ti-printer"></i> Imprimir / PDF</button>
        ${typeof cbModuloOculto==="function"&&cbModuloOculto("cronograma")?"":`<button class="btn sm" onclick="orcGerarCronograma('${t.id}')" title="Cria um cronograma (e24) com 1 atividade por etapa, valor com BDI"><i class="ti ti-timeline-event"></i> Gerar cronograma</button>`}
        <button class="btn sm" onclick="orcDuplicar('${t.id}')" title="Duplicar como nova versão"><i class="ti ti-copy"></i> Nova versão</button>
        <button class="btn sm" style="color:#b3261e" onclick="orcExcluir('${t.id}')"><i class="ti ti-trash"></i> Excluir</button>
      </div>
    </div>
    <div class="card" style="margin-bottom:14px">
      <div style="display:flex;gap:12px;flex-wrap:wrap;align-items:flex-end">
        <div class="field" style="flex:2;min-width:200px"><label>Nome</label><input value="${esc(t.nome)}" onchange="orcMeta('${t.id}','nome',this.value)"></div>
        <div class="field" style="flex:1;min-width:170px"><label>Projeto vinculado</label><select class="sinapi-uf" onchange="orcMeta('${t.id}','projeto_id',this.value)">${i}</select></div>
        <div class="field" style="width:120px"><label>BDI (%)</label><input type="number" min="0" step="0.1" value="${t.bdi!=null?t.bdi:0}" onchange="orcMeta('${t.id}','bdi',this.value)"></div>
      </div>
      <p class="page-sub" style="margin:8px 0 0;font-size:12px"><i class="ti ti-receipt"></i> Preços de referência: <strong>${a}</strong> (mude UF/regime na sub-aba SINAPI). Custo direto vem da SINAPI; BDI e preços finais são do RT.</p>
    </div>
    <div class="card" style="margin-bottom:14px">
      <h3 class="fin-h">Adicionar itens</h3>
      <div class="no-print" style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:8px">
        <input id="orc-busca" placeholder="Buscar composição SINAPI (código ou descrição)…" value="${esc(_orcBusca)}" oninput="orcBuscar('${t.id}',this.value)" style="flex:1;min-width:240px">
        <button class="btn sm" onclick="orcItemAvulso('${t.id}')"><i class="ti ti-plus"></i> Item avulso</button>
      </div>
      <div id="orc-result" class="orc-result"></div>
      ${orcTabelaHTML(t)}
    </div>
    <div class="card" id="orc-resumo">${orcResumoHTML(t)}</div>
    <p class="page-sub" style="margin-top:12px;font-size:12px"><i class="ti ti-info-circle"></i> Apoio ao planejamento — não substitui o orçamento do responsável técnico. A pré-montagem por IA a partir do projeto/EAP (f5/f14/f16) é evolução prevista no plano.</p>`}function orcTabelaHTML(t){const e=t.itens||[];if(!e.length)return`<p class="page-sub" style="margin:0">Sem itens. Busque uma composição SINAPI acima ou adicione um item avulso.</p>`;const i=e.map(o=>{const a=(Number(o.qtd)||0)*(Number(o.pu)||0);return`<tr>
      <td><input value="${esc(o.etapa||"")}" onchange="orcItemSet('${t.id}','${o.id}','etapa',this.value)" placeholder="etapa" style="min-width:90px"></td>
      <td>${o.tipo==="sinapi"?`<span class="code" style="font-size:11px;color:var(--text-3)">${esc(o.codigo)}</span> `:""}<input value="${esc(o.descricao||"")}" onchange="orcItemSet('${t.id}','${o.id}','descricao',this.value)" style="min-width:170px"></td>
      <td><input value="${esc(o.unidade||"")}" onchange="orcItemSet('${t.id}','${o.id}','unidade',this.value)" style="width:54px"></td>
      <td><input type="number" min="0" step="0.01" value="${o.qtd!=null?o.qtd:""}" onchange="orcItemSet('${t.id}','${o.id}','qtd',this.value)" style="width:72px"></td>
      <td><input type="number" min="0" step="0.01" value="${o.pu!=null?o.pu:""}" onchange="orcItemSet('${t.id}','${o.id}','pu',this.value)" style="width:96px"></td>
      <td class="price" style="text-align:right;white-space:nowrap">${orcBRL(a)}</td>
      <td class="no-print"><button class="btn sm icon-only" title="Remover" onclick="orcItemRemove('${t.id}','${o.id}')"><i class="ti ti-x"></i></button></td>
    </tr>`}).join("");return`<div style="overflow-x:auto"><table class="data" style="min-width:640px"><thead><tr>
    <th>Etapa</th><th>Descrição</th><th>Unid.</th><th>Qtd</th><th>PU</th><th style="text-align:right">Total</th><th class="no-print"></th>
    </tr></thead><tbody>${i}</tbody></table></div>`}function orcResumoHTML(t){const e=orcTotais(t);const i=Object.keys(e.porEtapa);const o=i.length?i.map(a=>`<tr><td>${esc(a)}</td><td class="price" style="text-align:right">${orcBRL(e.porEtapa[a])}</td><td style="text-align:right;color:var(--text-3)">${e.direto?(e.porEtapa[a]/e.direto*100).toFixed(1):"0"}%</td></tr>`).join(""):`<tr><td colspan="3" class="page-sub">Sem itens.</td></tr>`;return`<h3 class="fin-h">Resumo por etapa</h3>
    <table class="data" style="margin-bottom:14px"><thead><tr><th>Etapa</th><th style="text-align:right">Custo direto</th><th style="text-align:right">%</th></tr></thead><tbody>${o}</tbody></table>
    <div class="orc-tot">
      <div class="orc-tot-row"><span>Custo direto (SINAPI + avulsos)</span><strong>${orcBRL(e.direto)}</strong></div>
      <div class="orc-tot-row"><span>BDI (${e.bdiPct}%)</span><strong>${orcBRL(e.bdiVal)}</strong></div>
      <div class="orc-tot-row orc-tot-total"><span>Total do orçamento</span><strong>${orcBRL(e.total)}</strong></div>
    </div>`}function orcCsvCell(t){const e=String(t==null?"":t);return/[";\r\n]/.test(e)?'"'+e.replace(/"/g,'""')+'"':e}function orcCSV(t){const e=ORC.get(t);if(!e)return;const i=orcTotais(e);const o=[["Etapa","Tipo","Codigo","Descricao","Unidade","Qtd","PU","Total"]];(e.itens||[]).forEach(s=>o.push([s.etapa||"",s.tipo||"",s.codigo||"",s.descricao||"",s.unidade||"",orcNum(s.qtd),orcNum(s.pu),orcNum((Number(s.qtd)||0)*(Number(s.pu)||0))]));o.push([],["","","","","","","Custo direto",orcNum(i.direto)],["","","","","","","BDI "+i.bdiPct+"%",orcNum(i.bdiVal)],["","","","","","","TOTAL",orcNum(i.total)]);const a="\uFEFF"+o.map(s=>s.map(orcCsvCell).join(";")).join("\r\n");const r=new Blob([a],{type:"text/csv;charset=utf-8"});const n=document.createElement("a");n.href=URL.createObjectURL(r);n.download=(e.nome||"orcamento").replace(/[^\w\-]+/g,"_")+"_v"+(e.versao||1)+".csv";document.body.appendChild(n);n.click();n.remove();setTimeout(()=>URL.revokeObjectURL(n.href),2e3)}async function orcGerarCronograma(t){if(typeof cbModuloOculto==="function"&&cbModuloOculto("cronograma")){if(typeof toast==="function")toast(typeof CB_AVISO_FORA_DO_PILOTO==="string"?CB_AVISO_FORA_DO_PILOTO:"Esta área não faz parte do piloto.","info");return}if(typeof MODULOS!=="undefined"){try{await MODULOS.garantir("cronograma")}catch(c){}}if(typeof CRONO==="undefined"||typeof cAddDias!=="function"){toast("Módulo de cronograma indisponível.","error");return}const e=ORC.get(t);if(!e)return;const i=orcTotais(e);const o=Object.keys(i.porEtapa).filter(c=>c!=="(sem etapa)");if(!o.length){toast("Defina a etapa dos itens antes de gerar o cronograma.","warn");return}const a=1+i.bdiPct/100;let r=cHoje();const n=o.map(c=>{const d={id:CBStore.uuid(),etapa:c,nome:c,inicio:r,dur:15,valor:Math.round(i.porEtapa[c]*a),avanco:0,marco:false,dep:""};r=cAddDias(r,15);return d});const s=CBStore.uuid();CRONO.upsert({id:s,nome:(e.nome||"Obra")+" — cronograma",inicio:cHoje(),projeto_id:e.projeto_id||"",obs:"Gerado do orçamento "+(e.nome||""),atividades:n,dono:CBStore.uid()});toast("Cronograma criado a partir das etapas do orçamento. Ajuste as durações em Cronograma de obra.","success")}
