// Civilbook - Codigo proprietario. (c) 2026 CB Desenvolvimento de Software Não Customizável Inova Simples (I.S.).
// Todos os direitos reservados. Proibida copia, redistribuicao, modificacao ou
// uso sem autorizacao escrita do titular. Ver LICENSE (Lei 9.609/98 e 9.610/98).
// Componentes de terceiros mantem suas proprias licencas.
const PAY={ativo(){return!!(window.CB_CONFIG&&window.CB_CONFIG.PAGAMENTOS_ATIVO&&window.CB_CONFIG.SUPA_READY&&window.supa)},checkout(o){if(!this.ativo()){if(typeof toast==="function")toast("Pagamento online ainda não está ativo.","info");return}if(typeof AUTH==="undefined"||!AUTH.session()){if(typeof abrirAuth==="function")abrirAuth("cadastro");return}this._modalDoc(o)},_modalDoc(o){document.getElementById("cb-pay-modal")?.remove();const s=AUTH.session()&&AUTH.session().nome||"";const e=document.createElement("div");e.id="cb-pay-modal";e.style.cssText="position:fixed;inset:0;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;z-index:1000;padding:20px";e.onclick=n=>{if(n.target===e)e.remove()};const a=/^ia/.test(o)?"Civilbook IA":o==="pro-anual"?"PRO Anual":"PRO Mensal";const r=typeof PRECOS!=="undefined"&&PRECOS.rotulo?PRECOS.rotulo(o):null;const c=r?a+" ("+r+")":a;e.innerHTML=`<div class="card" style="max-width:420px;width:100%">
      <h3 style="margin-bottom:4px">Assinar ${c}</h3>
      <p class="page-sub" style="margin-bottom:14px">Informe seu CPF ou CNPJ para emitir a cobrança. No Asaas você escolhe PIX, boleto ou cartão.</p>
      <div class="field"><label>CPF ou CNPJ</label><input type="text" id="cb-pay-doc" inputmode="numeric" placeholder="Somente números"></div>
      <p id="cb-pay-erro" style="color:var(--red);font-size:13px;min-height:18px;margin:2px 0"></p>
      <div style="display:flex;gap:10px;justify-content:flex-end;margin-top:6px">
        <button class="btn" id="cb-pay-cancel">Cancelar</button>
        <button class="btn primary" id="cb-pay-go"><i class="ti ti-lock"></i> Ir para o pagamento</button>
      </div>
    </div>`;document.body.appendChild(e);const t=e.querySelector("#cb-pay-doc");const l=e.querySelector("#cb-pay-erro");const i=e.querySelector("#cb-pay-go");t.focus();e.querySelector("#cb-pay-cancel").onclick=()=>e.remove();const p=async()=>{const n=(t.value||"").replace(/\D/g,"");if(n.length!==11&&n.length!==14){l.textContent="CPF (11 dígitos) ou CNPJ (14 dígitos).";return}i.disabled=true;i.innerHTML=`<i class="ti ti-loader"></i> Gerando cobrança…`;const d=await this._iniciar(o,n,s);if(d&&d.erro){l.textContent=d.erro;i.disabled=false;i.innerHTML=`<i class="ti ti-lock"></i> Ir para o pagamento`}};i.onclick=p;t.addEventListener("keydown",n=>{if(n.key==="Enter")p()})},async _iniciar(o,s,e){try{const{data:{session:a}}=await window.supa.auth.getSession();const r=a&&a.access_token;const c=await fetch(window.CB_CONFIG.FUNCTIONS_URL+"/asaas-checkout",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+r,"apikey":window.CB_CONFIG.SUPABASE_ANON_KEY},body:JSON.stringify({plano:o,cpfCnpj:s,nome:e})});const t=await c.json().catch(()=>({}));if(t.url){window.location.href=t.url;return{ok:true}}return{erro:t.error||"Não foi possível iniciar o pagamento."}}catch(a){return{erro:"Falha ao conectar ao pagamento. Tente novamente."}}}};
