// Civilbook - Codigo proprietario. (c) 2026 CB Desenvolvimento de Software Não Customizável Inova Simples (I.S.).
// Todos os direitos reservados. Proibida copia, redistribuicao, modificacao ou
// uso sem autorizacao escrita do titular. Ver LICENSE (Lei 9.609/98 e 9.610/98).
// Componentes de terceiros mantem suas proprias licencas.
const ROADMAP={STATUS:{em_breve:["Em breve","pill-gray"],em_desenvolvimento:["Em desenvolvimento","pill-amber"],lancado:["Lançado","pill-teal"]},_ORD:{lancado:0,em_desenvolvimento:1,em_breve:2},ELIGIVEL_FASES:["C","E"],_supaOk(){return!!(typeof window!=="undefined"&&window.supa)},_esc(a){return String(a==null?"":a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")},elegivel(a){return this.ELIGIVEL_FASES.indexOf(String(a||"").toUpperCase())>=0},async publicados(){if(!this._supaOk())return[];const{data:a,error:e}=await window.supa.from("v_roadmap_publico").select("titulo,descricao,status,ordem").limit(50);if(e)return[];const r=this;return(a||[]).slice().sort((o,i)=>r._ORD[o.status]-r._ORD[i.status]||o.ordem-i.ordem)},async listarAdmin(){const{data:a,error:e}=await window.supa.from("roadmap_publico").select("*").order("ordem").order("created_at");if(e)throw e;return a||[]},async porTarefa(a){const{data:e}=await window.supa.from("roadmap_publico").select("*").eq("tarefa_id",a).maybeSingle();return e||null},async salvar(a){if(a.tarefa_id&&!this.elegivel(String(a.tarefa_id)[0]))throw new Error("Fase não elegível para divulgação pública.");const e={tarefa_id:a.tarefa_id||null,titulo:a.titulo,descricao:a.descricao||null,status:a.status||"em_breve",publicado:!!a.publicado,ordem:a.ordem||0};if(a.id){const{error:r}=await window.supa.from("roadmap_publico").update(e).eq("id",a.id);if(r)throw r}else if(e.tarefa_id){const r=await this.porTarefa(e.tarefa_id);if(r){const{error:o}=await window.supa.from("roadmap_publico").update(e).eq("id",r.id);if(o)throw o}else{const{error:o}=await window.supa.from("roadmap_publico").insert(e);if(o)throw o}}else{const{error:r}=await window.supa.from("roadmap_publico").insert(e);if(r)throw r}},async toggle(a,e){const{error:r}=await window.supa.from("roadmap_publico").update({publicado:!!e}).eq("id",a);if(r)throw r},async remover(a){const{error:e}=await window.supa.from("roadmap_publico").delete().eq("id",a);if(e)throw e},render(a){const e=typeof a==="string"?document.getElementById(a):a;if(!e)return;const r=this;this.publicados().then(o=>{if(!o.length){e.innerHTML="";return}e.innerHTML=`<div class="cb-roadmap-card">
        <div class="cb-roadmap-head"><i class="ti ti-rocket" aria-hidden="true"></i><span>Novidades e próximos passos</span></div>
        <div class="cb-roadmap-list">${o.map(i=>{const t=r.STATUS[i.status]||[i.status,"pill-gray"];return`<div class="cb-roadmap-item">
            <span class="pill ${t[1]} cb-roadmap-st">${r._esc(t[0])}</span>
            <div class="cb-roadmap-txt"><strong>${r._esc(i.titulo)}</strong>${i.descricao?`<span>${r._esc(i.descricao)}</span>`:""}</div>
          </div>`}).join("")}</div>
      </div>`}).catch(()=>{e.innerHTML=""})}};if(typeof window!=="undefined")window.ROADMAP=ROADMAP;
