// Civilbook - Codigo proprietario. (c) 2026 CB Desenvolvimento de Software Não Customizável Inova Simples (I.S.).
// Todos os direitos reservados. Proibida copia, redistribuicao, modificacao ou
// uso sem autorizacao escrita do titular. Ver LICENSE (Lei 9.609/98 e 9.610/98).
// Componentes de terceiros mantem suas proprias licencas.
const ZAP={numero(){return String(window.CB_CONFIG&&window.CB_CONFIG.WHATSAPP_NUMERO||"").replace(/\D/g,"")},ativo(){return this.numero().length>=10},TOPICOS:[{id:"planos",label:"Dúvidas sobre planos",icone:"ti-rosette",msg:"Olá! Tenho dúvidas sobre os planos do Civilbook."},{id:"produtos",label:"Conhecer os recursos",icone:"ti-apps",msg:"Olá! Quero saber mais sobre os recursos do Civilbook."},{id:"suporte",label:"Preciso de suporte",icone:"ti-lifebuoy",msg:"Olá! Preciso de ajuda no Civilbook."},{id:"outro",label:"Outro assunto",icone:"ti-message-2",msg:"Olá! Vim pelo site do Civilbook."}],TOPICOS_APP:[{id:"suporte",label:"Abrir chamado de suporte",icone:"ti-lifebuoy",aba:"suporte"},{id:"planos",label:"Planos e assinatura",icone:"ti-rosette",aba:"assinatura"},{id:"outro",label:"Outro assunto",icone:"ti-message-2",aba:"suporte"}],_origem(){try{return/app\.html|\/app(\b|$)/.test(location.pathname)?"app":"site"}catch(e){return"site"}},_noApp(){return!this._visitante&&this._origem()==="app"},link(e){return"https://wa.me/"+this.numero()+"?text="+encodeURIComponent(e+" (via "+this._origem()+")")},abrirTopico(e){if(this._noApp()){const t=this.TOPICOS_APP.find(o=>o.id===e)||this.TOPICOS_APP[this.TOPICOS_APP.length-1];this.fechar();if(typeof METRICS!=="undefined"&&METRICS.event){try{METRICS.event("ajuda",e,"app")}catch(o){}}if(typeof navigate==="function")navigate("conta",t.aba);return}const i=this.TOPICOS.find(t=>t.id===e)||this.TOPICOS[this.TOPICOS.length-1];window.open(this.link(i.msg),"_blank","noopener,noreferrer");if(typeof METRICS!=="undefined"&&METRICS.event){try{METRICS.event("whatsapp",e,this._origem())}catch(t){}}this.fechar()},_visitante:false,comoVisitante(){this._visitante=true;const e=document.getElementById("cb-zap");if(e){e.remove();this.montar()}},_desligado:false,desligar(){this._desligado=true;const e=document.getElementById("cb-zap");if(e)e.remove()},montar(){const e=this._noApp();if(!e&&!this.ativo())return;if(this._desligado)return;if(document.getElementById("cb-zap"))return;const i=document.createElement("div");i.id="cb-zap";i.className=e?"cb-zap cb-zap--ajuda":"cb-zap";const t=e?"Ajuda":"Fale no WhatsApp";const o=e?"ti ti-lifebuoy":"ti ti-brand-whatsapp";const s=e?"Fale com a equipe do Civilbook por aqui.":"Tire suas dúvidas — respondemos por aqui.";const r=e?`<i class="ti ti-info-circle" aria-hidden="true"></i> O chamado fica em Minha conta → Suporte, com a resposta da equipe.`:`<i class="ti ti-lock" aria-hidden="true"></i> Você será levado ao WhatsApp. Não enviamos seus dados automaticamente.`;i.innerHTML=`
      <div class="cb-zap-panel" id="cb-zap-panel" role="dialog" aria-label="${t}" hidden>
        <div class="cb-zap-head"><i class="${o}" aria-hidden="true"></i><div><strong>${t}</strong><span>${s}</span></div></div>
        <div class="cb-zap-topicos">${(e?this.TOPICOS_APP:this.TOPICOS).map(a=>`<button type="button" onclick="ZAP.abrirTopico('${a.id}')"><i class="ti ${a.icone}" aria-hidden="true"></i>${a.label}</button>`).join("")}</div>
        <div class="cb-zap-foot">${r}</div>
      </div>
      <button type="button" class="cb-zap-fab" id="cb-zap-fab" aria-label="${t}" aria-expanded="false" onclick="ZAP.alternar()"><i class="${o}" aria-hidden="true"></i></button>`;document.body.appendChild(i);if(this._ouvindo)return;this._ouvindo=true;document.addEventListener("keydown",a=>{if(a.key==="Escape")this.fechar()});document.addEventListener("click",a=>{const n=document.getElementById("cb-zap");if(n&&!n.contains(a.target))this.fechar()})},_aberto(){const e=document.getElementById("cb-zap-panel");return!!(e&&!e.hasAttribute("hidden"))},alternar(){this._aberto()?this.fechar():this.abrir()},abrir(){const e=document.getElementById("cb-zap-panel"),i=document.getElementById("cb-zap-fab"),t=document.getElementById("cb-zap");if(e)e.removeAttribute("hidden");if(i)i.setAttribute("aria-expanded","true");if(t)t.classList.add("open")},fechar(){const e=document.getElementById("cb-zap-panel"),i=document.getElementById("cb-zap-fab"),t=document.getElementById("cb-zap");if(e)e.setAttribute("hidden","");if(i)i.setAttribute("aria-expanded","false");if(t)t.classList.remove("open")}};if(typeof window!=="undefined")window.ZAP=ZAP;(function(){function e(){try{ZAP.montar()}catch(i){}}if(document.readyState!=="loading")e();else document.addEventListener("DOMContentLoaded",e)})();
